In [ ]:
## numpy-- numerical python
## mathamatical and scientific computing liberary
## array -- collectio ofsimilar type of data

## list vs array-- list ma multiple data types lta h or array m 1 de data type hotah

## array -- 1d --2d ---3d
#1d-- assume as a list
#2d-- arrar ke array -- matrices -- row and columns -- m x n -- shap
#3darray== 2d array ki aarray

## pip install numpy -- run in terminal




In [1]:
import numpy as np


In [3]:
## array creation 
arr1 = np.array([1,2,3,4,5])
#print(arr1)
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.arange(1,6)
arr2

array([1, 2, 3, 4, 5])

In [6]:
arr3 = np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

In [7]:
arr4 = np.ones(5)
arr4

array([1., 1., 1., 1., 1.])

In [ ]:
arr5 = np.linspace(1,10,5)  # 1 - 10 --> range and 5 is no. of elements . mtlb 1 to 10 ka bech m ketna no.cheya
arr5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
## 2d array

In [ ]:
arr6 = np.arange(60).reshape(6,10) ## reshap total no. ka multiple 6 rows 10 coloumns
arr6   

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [13]:
arr6.shape ## rows and columns
arr6.dtype
arr6.size
arr6.ndim

2

In [ ]:
## random numbers sa error create krne h tb
arr8 = np.random.random(10) ## hr baar alg alg np. melnga o/p m
arr8

array([0.85424319, 0.59805363, 0.00252655, 0.34372876, 0.24017063,
       0.78156739, 0.0504109 , 0.46901008, 0.06093607, 0.70375857])

In [ ]:
arr9 = np.random.randint(1,10,100) ## random no. int m
arr9

array([4, 7, 8, 4, 2, 7, 3, 4, 6, 1, 5, 7, 4, 3, 4, 7, 2, 5, 4, 9, 8, 6,
       5, 6, 2, 2, 2, 2, 1, 1, 7, 7, 5, 6, 9, 2, 4, 8, 3, 7, 7, 4, 9, 6,
       6, 2, 3, 8, 1, 6, 2, 5, 1, 1, 1, 5, 3, 5, 4, 5, 1, 2, 4, 2, 6, 6,
       7, 9, 5, 8, 6, 5, 2, 9, 1, 5, 8, 7, 1, 1, 2, 3, 4, 6, 7, 8, 4, 7,
       8, 8, 9, 5, 7, 5, 8, 8, 6, 2, 5, 1], dtype=int32)

In [ ]:
print(arr6.shape) ## rows and columns
arr6.dtype
arr6.size
arr6.ndim

arr6.T.shape  ## transpose

(6, 10)


(10, 6)

In [ ]:
## higher dimension array ko 1 dimension array m convert kr dta h 
arr6.flatten() 
arr6.ravel()
## both performing same work

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
##3d array
# arr9 = np.random.randint(1,10,(3,4))
# arr9

array([[6, 9, 2, 5],
       [4, 4, 3, 3],
       [8, 2, 9, 6]], dtype=int32)

In [22]:
arr9 = np.arange(225).reshape(3,15,5)  ## 15,5 --> rows and 3--> table
arr9

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [23]:
np.max(arr9)
np.min(arr9)
np.mean(arr9)
np.median(arr9)
np.std(arr9)

np.float64(64.95126378036586)

In [11]:
arr7 = np.ones((2,3))
arr7

array([[1., 1., 1.],
       [1., 1., 1.]])